- name: Install dependencies
  apt:
    name:
        - build-essential
        - git
        - meson
        - ninja-build
        - valac
        - pkg-config
        - libgirepository1.0-dev
        - libgtk-3-dev
        - libsoup2.4-dev
        - libjson-glib-dev
        - libwebkit2gtk-4.0-dev
        - libsqlite3-dev
        - libsecret-1-dev
        - libnotify-dev
        - libxml2-dev
        - librest-dev=0.8.1-1
        - libgee-0.8-dev
        - libgstreamer1.0-dev
        - libgstreamer-plugins-base1.0-dev
        - libgoa-1.0-dev
        - libcurl4-gnutls-dev
        - libpeas-dev
        - libgranite-dev
        - libhandy-1-dev
        - openjdk-11-jdk
        - libncurses5

################################################################################################################################################

- name: Clone repository libdecsync
  git:
    repo: "https://github.com/39aldo39/libdecsync"
    dest: /tmp/libdecsync
    version: "master"
    force: false
  ignore_errors: true

- name: Run make
  shell: 'make'
  args:
    chdir: /tmp/libdecsync/

- name: Run make install
  shell: 'make install'
  args:
    chdir: /tmp/libdecsync/

################################################################################################################################################

- name: Clone repository
  git:
    repo: "{{ feedreader_repo }}"
    dest: /tmp/feedreader
    version: "{{ feedreader_version }}"
    force: false
    recursive: true
  ignore_errors: true

- name: Create build directory
  file: path=/tmp/feedreader/build state=directory

- name: Check that /tmp/feedreader/build/Makefile exists
  stat:
    path: /tmp/feedreader/build/Makefile
  register: stat_result

#- name: Run cmake
#  command: 'cmake .. chdir=/tmp/feedreader/build'
#  when: stat_result.stat.exists == False

####- name: save patch to disk
####  copy:
####    content: "{{ patch }}"
####    dest: /tmp/feedreader.patch

####- name: applay patch
####  ansible.posix.patch:
####    src: /tmp/feedreader.patch
####    dest: /tmp/feedreader/meson.build
####    remote_src: true
####    strip: 1

- name: Run meson build
  shell: 'meson build'
  args:
    chdir: /tmp/feedreader/
  when: stat_result.stat.exists == False

- name: Check that /tmp/feedreader/build/feedreader exists
  stat:
    path:  /tmp/feedreader/build/feedreader
  register: stat_result

- name: Run make
  shell: 'ninja -C build install'
  args:
    chdir: /tmp/feedreader/
  when: stat_result.stat.exists == False

####- name: Check that /usr/local/bin/feedreader exists
####  stat:
####    path:  /usr/local/bin/feedreader
####  register: stat_result

####- name: Run make install
####  command: 'make install chdir=/tmp/feedreader/build'
####  when: stat_result.stat.exists == False
